setup: &setup
  adapter: postgresql
  encoding: unicode
  pool: 10
  timeout: 5000

development:
  <<: *setup
  database: nptv_dev_center_development
  username: postgres
  password:

test:
  <<: *setup
  database: nptv_dev_center_test
  username: postgres
  password:

staging:
  <<: *setup
  database: nptv_dev_center_development
  username: postgres
  password:

production:
  <<: *setup
  database: devcenter_nptv_production
  username: devcenter_nptv_production
  password: